security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_homepage
                enable_csrf: true
            logout:
                path: app_logout
                target: app_homepage
                enable_csrf: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800

    role_hierarchy:
        ROLE_EMPLOYE: ROLE_USER
        ROLE_ADMIN: [ROLE_EMPLOYE, ROLE_USER]

    access_control:
        - { path: ^/espace-admin, roles: ROLE_ADMIN }
        - { path: ^/espace-employe, roles: ROLE_EMPLOYE }
        - { path: ^/espace-utilisateur, roles: ROLE_USER }
        - { path: ^/commande, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
